SELECT * FROM EMPLOYEE_SALARY FETCH FIRST 10 ROWS ONLY;
CREATE TABLE DEPARTMENT (
 DEPT_ID NUMBER PRIMARY KEY,
 DEPT_NAME VARCHAR2(50),
 EMPLOYEE_ID NUMBER
);
INSERT INTO DEPARTMENT (DEPT_ID, DEPT_NAME, EMPLOYEE_ID) VALUES (1, 'Finance', 1);
INSERT INTO DEPARTMENT (DEPT_ID, DEPT_NAME, EMPLOYEE_ID) VALUES (2, 'IT', 2);
INSERT INTO DEPARTMENT (DEPT_ID, DEPT_NAME, EMPLOYEE_ID) VALUES (3, 'HR', 3);
INSERT INTO DEPARTMENT (DEPT_ID, DEPT_NAME, EMPLOYEE_ID) VALUES (4, 'Marketing', 4);
INSERT INTO DEPARTMENT (DEPT_ID, DEPT_NAME, EMPLOYEE_ID) VALUES (5, 'Finance', 5);
INSERT INTO DEPARTMENT (DEPT_ID, DEPT_NAME, EMPLOYEE_ID) VALUES (6, 'IT', 6);
INSERT INTO DEPARTMENT (DEPT_ID, DEPT_NAME, EMPLOYEE_ID) VALUES (7, 'HR', 7);
INSERT INTO DEPARTMENT (DEPT_ID, DEPT_NAME, EMPLOYEE_ID) VALUES (8, 'Marketing', 8);
INSERT INTO DEPARTMENT (DEPT_ID, DEPT_NAME, EMPLOYEE_ID) VALUES (9, 'Finance', 9);
INSERT INTO DEPARTMENT (DEPT_ID, DEPT_NAME, EMPLOYEE_ID) VALUES (10, 'IT', 10);
COMMIT;
CREATE TABLE ATTENDANCE (
   ATTENDANCE_ID NUMBER PRIMARY KEY,
   EMPLOYEE_ID NUMBER,
   CHECK_IN DATE,
   CHECK_OUT DATE,
   CONSTRAINT fk_emp_att FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE_SALARY(ID)
);
DESC EMPLOYEE_SALARY;
ALTER TABLE EMPLOYEE_SALARY
ADD CONSTRAINT pk_emp_salary_id PRIMARY KEY (ID);

INSERT INTO ATTENDANCE VALUES (1, 1, TO_DATE('2025-05-01 09:00', 'YYYY-MM-DD HH24:MI'), TO_DATE('2025-05-01 17:00', 'YYYY-MM-DD HH24:MI'));
INSERT INTO ATTENDANCE VALUES (2, 2, TO_DATE('2025-05-01 09:30', 'YYYY-MM-DD HH24:MI'), TO_DATE('2025-05-01 18:00', 'YYYY-MM-DD HH24:MI'));
COMMIT;

CREATE TABLE PAYROLL (
   PAYROLL_ID NUMBER PRIMARY KEY,
   EMPLOYEE_ID NUMBER,
   BASIC_SALARY NUMBER,
   BONUS NUMBER,
   DEDUCTIONS NUMBER,
   MONTH VARCHAR2(10),
   CONSTRAINT fk_emp_payroll FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE_SALARY(ID)
);

INSERT INTO PAYROLL VALUES (1, 1, 200000, 30000, 5000, 'May');
INSERT INTO PAYROLL VALUES (2, 2, 40000, 7000, 2000, 'May');

COMMIT;

CREATE TABLE PAYSLIP (
   PAYSLIP_ID NUMBER PRIMARY KEY,
   EMPLOYEE_ID NUMBER,
   PAYROLL_ID NUMBER,
   NET_SALARY NUMBER,
   GENERATED_DATE DATE,
   CONSTRAINT fk_emp_payslip FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE_SALARY(ID),
   CONSTRAINT fk_payroll_payslip FOREIGN KEY (PAYROLL_ID) REFERENCES PAYROLL(PAYROLL_ID)
);

INSERT INTO PAYSLIP VALUES (1, 1, 1, 225000, SYSDATE);
INSERT INTO PAYSLIP VALUES (2, 2, 2, 45000, SYSDATE);
COMMIT;

CREATE TABLE EMPLOYEE_REPORT (
   REPORT_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
   EMPLOYEE_ID NUMBER,
   SALARY NUMBER,
   HOURS_WORKED NUMBER,
   GENERATED_ON DATE DEFAULT SYSDATE
);
