CREATE OR REPLACE VIEW MIS_DASHBOARD AS
SELECT 
    e.ID                    AS EMPLOYEE_ID,
    e.NAME                  AS EMPLOYEE_NAME,
    e.GENDER,
    e.AGE,
    e.EXPERIENCE_YEARS,
    d.DEPT_NAME,
    a.CHECK_IN,
    a.CHECK_OUT,
    ROUND(
      (
        TO_DATE(a.CHECK_OUT, 'DD-MM-YY HH24:MI') - TO_DATE(a.CHECK_IN, 'DD-MM-YY HH24:MI')
      ) * 24,
      2
    ) AS HOURS_WORKED,
    p.BASIC_SALARY,
    p.BONUS,
    p.DEDUCTIONS,
    ps.NET_SALARY,
    ps.GENERATED_DATE       AS PAYSLIP_DATE,
    r.GENERATED_ON          AS REPORT_GENERATED_ON
FROM 
    EMPLOYEE_SALARY e
LEFT JOIN DEPARTMENT d        ON e.ID = d.EMPLOYEE_ID
LEFT JOIN ATTENDANCE a        ON e.ID = a.EMPLOYEE_ID
LEFT JOIN PAYROLL p           ON e.ID = p.EMPLOYEE_ID
LEFT JOIN PAYSLIP ps          ON p.PAYROLL_ID = ps.PAYROLL_ID
LEFT JOIN EMPLOYEE_REPORT r   ON e.ID = r.EMPLOYEE_ID;
